diff --git a/Dockerfile b/Dockerfile
index 87ef00b..75dc5d7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,8 +13,8 @@
 FROM centos:7.4.1708
 
 # Proxy configuration
-#ENV http_proxy  "http://your.actual_http_proxy.com:your_port"
-#ENV https_proxy "https://your.actual_https_proxy.com:your_port"
+ENV http_proxy  "http://child-prc.intel.com:913"
+ENV https_proxy "https://child-prc.intel.com:913"
 #ENV ftp_proxy   "http://your.actual_ftp_proxy.com:your_port"
 
 
@@ -26,6 +26,8 @@ ARG MYUID=1000
 
 ENV container=docker
 
+RUN echo "proxy=http://child-prc.intel.com:913" >> /etc/yum.conf
+
 # Download required dependencies by mirror/build processes.
 # Notice there are 3 invocations to yum package manage.
 # 1) Enable EPEL repository.
